// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi-UsxPDEONi5VsHYAhQ6ALrkp4jp_LuE',
    appId: '1:1040434160892:web:4a1b2c442c9e1273b56379',
    messagingSenderId: '1040434160892',
    projectId: 'binusrent',
    authDomain: 'binusrent.firebaseapp.com',
    storageBucket: 'binusrent.appspot.com',
    measurementId: 'G-9T5E7DETLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbUoOhFbZVimdHc8TBNpwFGyBvqKjmERY',
    appId: '1:1040434160892:android:b1586ce65fe20db8b56379',
    messagingSenderId: '1040434160892',
    projectId: 'binusrent',
    storageBucket: 'binusrent.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUY60IFahT2TAgtf7dVI0ukPkpr2_cces',
    appId: '1:1040434160892:ios:4dc925ec674b7701b56379',
    messagingSenderId: '1040434160892',
    projectId: 'binusrent',
    storageBucket: 'binusrent.appspot.com',
    iosBundleId: 'inc.notchg.rentapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUY60IFahT2TAgtf7dVI0ukPkpr2_cces',
    appId: '1:1040434160892:ios:630b9373f487811cb56379',
    messagingSenderId: '1040434160892',
    projectId: 'binusrent',
    storageBucket: 'binusrent.appspot.com',
    iosBundleId: 'inc.notchg.rentapp.RunnerTests',
  );
}
